spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/esports_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: 12345678901234567890123456789012
  expiration: 3600000
